import { APP_PREFIX_PATH } from '@/constants/route.constant'
import { NAV_ITEM_TYPE_TITLE, NAV_ITEM_TYPE_COLLAPSE, NAV_ITEM_TYPE_ITEM } from '@/constants/navigation.constant'
import { ADMIN, USER } from '@/constants/roles.constant'
import type { NavigationTree } from '@/@types/navigation'

const appsNavigationConfig: NavigationTree[] = [
    {
        key: 'apps',
        path: '',
        title: 'APPS',
        translateKey: 'nav.apps',
        icon: 'apps',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [ADMIN, USER],
        subMenu: [
            {
                key: 'apps.homePage',
                path: `${APP_PREFIX_PATH}/homePage`,
                title: 'Home',
                translateKey: 'nav.appsHomepage.homePage',
                icon: 'home',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [],
            },
            {
                key: 'apps.orderManagement',
                path: '',
                title: 'Order Management',
                translateKey: 'nav.appsOrderManagement.orderManagement',
                icon: 'sales',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'appsOrderManagement.orderList',
                        path: `${APP_PREFIX_PATH}/orders`,
                        title: 'New Orders',
                        translateKey: 'nav.appsOrderManagement.orderList',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsOrderManagement.returnOrderList',
                        path: `${APP_PREFIX_PATH}/returnOrders`,
                        title: 'Return Orders',
                        translateKey: 'nav.appsOrderManagement.returnOrderList',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsOrderManagement.returnItems',
                        path: `${APP_PREFIX_PATH}/returnItems`,
                        title: 'Return Items',
                        translateKey: 'nav.appsOrderManagement.returnItems',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsOrderManagement.deliveryOrders',
                        path: `${APP_PREFIX_PATH}/deliveryOrders`,
                        title: 'Forward Delivery',
                        translateKey: 'nav.appsOrderManagement.deliveryOrders',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsOrderManagement.exchangeOrders',
                        path: `${APP_PREFIX_PATH}/exchangeOrders`,
                        title: 'Exchange Orders',
                        translateKey: 'nav.appsOrderManagement.exchangeOrders',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsOrderManagement.reverseDelivery',
                        path: `${APP_PREFIX_PATH}/reverseDelivery`,
                        title: 'Reverse Delivery',
                        translateKey: 'nav.appsOrderManagement.reverseDelivery',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsOrderManagement.skuOrderHistory',
                        path: `${APP_PREFIX_PATH}/skuOrderHistory`,
                        title: 'Sku Order History',
                        translateKey: 'nav.appsOrderManagement.skuOrderHistory',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                ],
            },

            // Inventory Management.................................................
            {
                key: 'apps.inventoryManagement',
                path: '',
                title: 'Inventory Management',
                translateKey: 'nav.appsInventoryManagement.inventoryManagement',
                icon: 'inventory',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'appsInventoryManagement.inwards',
                        path: `${APP_PREFIX_PATH}/goods/received`,
                        title: 'Inwards',
                        translateKey: 'nav.appsInventoryManagement.inwards',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsInventoryManagement.quality_check',
                        path: `${APP_PREFIX_PATH}/goods/qualitycheck`,
                        title: 'Upload GRN',
                        translateKey: 'nav.appsInventoryManagement.quality_check',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsInventoryManagement.quality_checkList',
                        path: `${APP_PREFIX_PATH}/goods/qualitycheckList`,
                        title: 'Quality Check List',
                        translateKey: 'nav.appsInventoryManagement.quality_check',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsInventoryManagement.gdn',
                        path: `${APP_PREFIX_PATH}/goods/gdn`,
                        title: 'Dispatches',
                        translateKey: 'nav.appsInventoryManagement.gdn',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },

                    {
                        key: 'appsInventoryManagement.gdn_quality_check',
                        path: `${APP_PREFIX_PATH}/goods/gdn_qualitycheck`,
                        title: 'Upload GDN',
                        translateKey: 'nav.appsInventoryManagement.gdn_quality_check',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },

                    {
                        key: 'appsInventoryManagement.transfer',
                        path: `${APP_PREFIX_PATH}/goods/transfer`,
                        title: 'Transfers',
                        translateKey: 'nav.appsInventoryManagement.transfers',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsInventoryManagement.transfer_quality_check',
                        path: `${APP_PREFIX_PATH}/goods/transfer_qualitycheck`,
                        title: 'Upload GTN',
                        translateKey: 'nav.appsInventoryManagement.gdn_quality_check',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },

                    {
                        key: 'appsInventoryManagement.stock_overview',
                        path: `${APP_PREFIX_PATH}/stockOverview`,
                        title: 'Stock Overview',
                        translateKey: 'nav.appsInventoryManagement.stock_overview',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsVendorManagement.inventoryLocation',
                        path: `${APP_PREFIX_PATH}/inventoryLocation`,
                        title: 'Inventory Location',
                        translateKey: 'nav.appsVendorManagement.inventoryLocation',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsInventoryManagement.printer',
                        path: `${APP_PREFIX_PATH}/printer`,
                        title: 'Sku Tag Printer',
                        translateKey: 'nav.appsInventoryManagement.printer',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsInventoryManagement.material',
                        path: `${APP_PREFIX_PATH}/material`,
                        title: 'Location CSV Download',
                        translateKey: 'nav.appsInventoryManagement.material',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },

                    {
                        key: 'appsInventoryManagement.indent',
                        path: `${APP_PREFIX_PATH}/goods/indent/`,
                        title: 'Indent ',
                        translateKey: 'nav.appsInventoryManagement.indent',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsInventoryManagement.indentUpload',
                        path: `${APP_PREFIX_PATH}/goods/indentUpload/`,
                        title: 'Indent Upload',
                        translateKey: 'nav.appsInventoryManagement.indentUploader',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsInventoryManagement.rtv',
                        path: `${APP_PREFIX_PATH}/goods/rtv`,
                        title: 'RTV',
                        translateKey: 'nav.appsInventoryManagement.rtv',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsInventoryManagement.rtvUpload',
                        path: `${APP_PREFIX_PATH}/goods/rtvUpload`,
                        title: 'RTV Upload',
                        translateKey: 'nav.appsInventoryManagement.rtvUploader',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                ],
            },

            //......................................................................

            // Vendor management.....................................................................

            {
                key: 'apps.vendorManagement',
                path: '',
                title: 'Brand Dashboard',
                translateKey: 'nav.appsVendorManagement.vendorManagement',
                icon: 'brand',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'appsVendorManagement.businessDetails',
                        path: `${APP_PREFIX_PATH}/vendor/Details`,
                        title: 'Business Details',
                        translateKey: 'nav.appsVendorManagement.businessDetails',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsVendorManagement.salesOverview',
                        path: `${APP_PREFIX_PATH}/vendor/sales`,
                        title: 'Sales Overview',
                        translateKey: 'nav.appsVendorManagement.salesOverview',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    // {
                    //     key: 'appsVendorManagement.shipments',
                    //     path: `${APP_PREFIX_PATH}/vendor/shipments`,
                    //     title: 'Shipments',
                    //     translateKey: 'nav.appsInventoryManagement.shipments',
                    //     icon: '',
                    //     type: NAV_ITEM_TYPE_ITEM,
                    //     authority: [ADMIN, USER],
                    //     subMenu: [],
                    // },
                    {
                        key: 'appsVendorManagement.users',
                        path: `${APP_PREFIX_PATH}/vendor/users`,
                        title: 'Users',
                        translateKey: 'nav.appsInventoryManagement.users',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsVendorManagement.catalog',
                        path: `${APP_PREFIX_PATH}/vendor/catalog`,
                        title: 'Catalog Overview',
                        translateKey: 'nav.appsInventoryManagement.catalog',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsVendorManagement.stockOverview',
                        path: `${APP_PREFIX_PATH}/vendor/stock`,
                        title: 'Stock Overview',
                        translateKey: 'nav.appsVendorManagement.stockOverview',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },

                    {
                        key: 'appsVendorManagement.orders',
                        path: `${APP_PREFIX_PATH}/vendor/orders`,
                        title: 'Orders',
                        translateKey: 'nav.appsVendorManagement.orders',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },

                    {
                        key: 'appsVendorManagement.returns',
                        path: `${APP_PREFIX_PATH}/vendor/returns`,
                        title: 'Returns',
                        translateKey: 'nav.appsVendorManagement.returns',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsVendorManagement.accounts',
                        path: `${APP_PREFIX_PATH}/vendor/accounts`,
                        title: 'Accounting Details',
                        translateKey: 'nav.appsVendorManagement.accounts',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                ],
            },

            //.......................................................................................

            {
                key: 'apps.category',
                path: '',
                title: 'Catalog Management',
                translateKey: 'nav.appsCategory.category',
                icon: 'category',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'appsCategory.uploadCatalog',
                        path: `${APP_PREFIX_PATH}/catalog/upload`,
                        title: 'Catalog Upload',
                        translateKey: 'nav.appsCategory.uploadCatalog',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsCategory.products',
                        path: `${APP_PREFIX_PATH}/catalog/products`,
                        title: 'Products',
                        translateKey: 'nav.appsCategory.products',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsCategory.division',
                        path: `${APP_PREFIX_PATH}/category/division`,
                        title: 'Division',
                        translateKey: 'nav.appsCategory.division',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsCategory.category',
                        path: `${APP_PREFIX_PATH}/category/category`,
                        title: 'Category',
                        translateKey: 'nav.appsCategory.category',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsCategory.subCategory',
                        path: `${APP_PREFIX_PATH}/category/subCategory`,
                        title: 'Sub Category',
                        translateKey: 'nav.appsCategory.subCategory',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsCategory.productType',
                        path: `${APP_PREFIX_PATH}/category/productType`,
                        title: 'Product Type',
                        translateKey: 'nav.appsCategory.productType',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsCategory.brand',
                        path: `${APP_PREFIX_PATH}/category/brand`,
                        title: 'Brand',
                        translateKey: 'nav.appsCategory.brand',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsCategory.productTags',
                        path: `${APP_PREFIX_PATH}/catalog/productTags`,
                        title: 'Product Tags',
                        translateKey: 'nav.appsCategory.productTags',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsCategory.productLock',
                        path: `${APP_PREFIX_PATH}/category/productLock`,
                        title: 'Product Lock',
                        translateKey: 'nav.appsCategory.productLock',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsCategory.uploader',
                        path: `${APP_PREFIX_PATH}/category/uploader`,
                        title: 'Uploader',
                        translateKey: 'nav.appsCategory.productFeedback',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsCategory.filters',
                        path: `${APP_PREFIX_PATH}/category/filters`,
                        title: 'Filters Table',
                        translateKey: 'nav.appsCategory.filters',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                ],
            },
            //..........................................................................................................
            {
                key: 'apps.OrgManagement',
                path: '',
                title: 'Organization Management',
                translateKey: 'nav.appsOrgManagement.OrgManagement',
                icon: 'org',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'appsOrgManagement.sellers',
                        path: `${APP_PREFIX_PATH}/sellers`,
                        title: 'Sellers',
                        translateKey: 'nav.appsOrgManagement.sellers',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsOrgManagement.po',
                        path: `${APP_PREFIX_PATH}/po`,
                        title: 'Purchase Orders',
                        translateKey: 'nav.appsOrgManagement.po',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsOrgManagement.poCatalogHistory',
                        path: `${APP_PREFIX_PATH}/poCatalogHistory`,
                        title: 'PO Catalog History',
                        translateKey: 'nav.appsOrgManagement.po',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },

                    {
                        key: 'appsOrgManagement.sellerTemplate',
                        path: `${APP_PREFIX_PATH}/sellerTemplate`,
                        title: 'Templates',
                        translateKey: 'nav.appsOrgManagement.sellerTemplate',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsOrgManagement.stores',
                        path: `${APP_PREFIX_PATH}/stores`,
                        title: 'Fullfillment Center',
                        translateKey: 'nav.appsOrgManagement.stores',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsOrgManagement.users',
                        path: `${APP_PREFIX_PATH}/users`,
                        title: 'Users',
                        translateKey: 'nav.appsOrgManagement.users',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsOrgManagement.accessManagement',
                        path: `${APP_PREFIX_PATH}/accessManagement`,
                        title: 'Access Management',
                        translateKey: 'nav.appsOrgManagement.accessManagement',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                ],
            },

            // Creator Post.......................................................................................................

            {
                key: 'apps.creatorPost',
                path: `${APP_PREFIX_PATH}/userposts/approval`,
                title: 'Creator Posts',
                translateKey: 'nav.apps.creatorPost.creatorPost',
                icon: 'reels',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'appscreatorPost.postApproval',
                        path: `${APP_PREFIX_PATH}/postApproval`,
                        title: 'Post Approval',
                        translateKey: 'nav.appsOrgManagement.postApproval',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appscreatorPost.uploadPost',
                        path: `${APP_PREFIX_PATH}/uploadPost`,
                        title: 'Upload Post',
                        translateKey: 'nav.appsOrgManagement.uploadPost',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                ],
            },

            // Offers and Promotions.......

            {
                key: 'apps.offers',
                path: `${APP_PREFIX_PATH}/userposts/approval`,
                title: 'Offers & Promotions',
                translateKey: 'nav.apps.offers.offers',
                icon: 'offers',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'appsAppSettings.coupons',
                        path: `${APP_PREFIX_PATH}/appSettings/coupons`,
                        title: 'Coupons',
                        translateKey: 'nav.appsAppSettings.coupons',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsAppSettings.couponsSeries',
                        path: `${APP_PREFIX_PATH}/appSettings/couponsSeries`,
                        title: 'Coupons Series',
                        translateKey: 'nav.appsAppSettings.couponsSeries',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsAppSettings.offers',
                        path: `${APP_PREFIX_PATH}/appSettings/offers`,
                        title: 'Offers',
                        translateKey: 'nav.appsAppSettings.offers',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsAppSettings.eventSeries',
                        path: `${APP_PREFIX_PATH}/appSettings/eventSeries`,
                        title: 'Promotional Event',
                        translateKey: 'nav.appsAppSettings.eventSeries',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsOffers.markdownPrices',
                        path: `${APP_PREFIX_PATH}/markdownPrices`,
                        title: 'Markdown Prices',
                        translateKey: 'nav.appsOffers.markdownPrices',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsOffers.offerAndPromotions',
                        path: `${APP_PREFIX_PATH}/offerAndPromotions`,
                        title: 'Promotion Engine',
                        translateKey: 'nav.appsOffers.OfferAndPromotions',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    // {
                    //     key: 'appsOffers.uploadPost',
                    //     path: `${APP_PREFIX_PATH}/uploadPost`,
                    //     title: 'Upload Post',
                    //     translateKey: 'nav.appsOrgManagement.uploadPost',
                    //     icon: '',
                    //     type: NAV_ITEM_TYPE_ITEM,
                    //     authority: [ADMIN, USER],
                    //     subMenu: [],
                    // },
                ],
            },

            // .............................................................................................................

            {
                key: 'apps.appSettings',
                path: '',
                title: 'App Settings',
                translateKey: 'nav.appsAppSettings.appSettings',
                icon: 'appsettings',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'appsAppSettings.banners',
                        path: `${APP_PREFIX_PATH}/appSettings/banners`,
                        title: 'Banners',
                        translateKey: 'nav.appsAppSettings.banners',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    // {
                    //     key: 'appsAppSettings.pageSettings',
                    //     path: `${APP_PREFIX_PATH}/appSettings/pageSettings`,
                    //     title: 'Page Settings',
                    //     translateKey: 'nav.appsAppSettings.pageSettings',
                    //     icon: '',
                    //     type: NAV_ITEM_TYPE_ITEM,
                    //     authority: [ADMIN, USER],
                    //     subMenu: [],
                    // },
                    {
                        key: 'appsAppSettings.policies',
                        path: `${APP_PREFIX_PATH}/appSettings/policies`,
                        title: 'Policies',
                        translateKey: 'nav.appsAppSettings.policies',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsAppSettings.careers',
                        path: `${APP_PREFIX_PATH}/appSettings/careers`,
                        title: 'careers',
                        translateKey: 'nav.appsAppSettings.careers',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsAppSettings.seoSettings',
                        path: `${APP_PREFIX_PATH}/appSettings/seoSettings`,
                        title: 'Seo Settings',
                        translateKey: 'nav.appsAppSettings.seoSettings',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },

                    {
                        key: 'appsAppSettings.newPageSettings',
                        path: `${APP_PREFIX_PATH}/appSettings/newPageSettings`,
                        title: 'Page Settings',
                        translateKey: 'nav.appsAppSettings.newPageSettings',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsAppSettings.pageSubPage',
                        path: `${APP_PREFIX_PATH}/appSettings/pageSubPage`,
                        title: 'SubPage',
                        translateKey: 'nav.appsAppSettings.pageSubPage',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                ],
            },

            {
                key: 'apps.communcication',
                path: `${APP_PREFIX_PATH}/communication`,
                title: 'Communication',
                translateKey: 'nav.appsCommuncication.communcication',
                icon: 'communication',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    // {
                    //     key: 'appsCommuncication.groups',
                    //     path: `${APP_PREFIX_PATH}/appsCommuncication/groups`,
                    //     title: 'Groups',
                    //     translateKey: 'nav.appsCommuncication.groups',
                    //     icon: '',
                    //     type: NAV_ITEM_TYPE_ITEM,
                    //     authority: [ADMIN, USER],
                    //     subMenu: [],
                    // },
                    {
                        key: 'appsCommuncication.cohorts',
                        path: `${APP_PREFIX_PATH}/appsCommuncication/cohorts`,
                        title: 'User Cohorts',
                        translateKey: 'nav.appsCommuncication.cohorts',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsCommuncication.sendNotification',
                        path: `${APP_PREFIX_PATH}/appsCommuncication/sendNotification`,
                        title: 'Send Notification',
                        translateKey: 'nav.appsCommuncication.sendNotification',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsCommuncication.urlShortner',
                        path: `${APP_PREFIX_PATH}/appsCommuncication/urlShortner`,
                        title: 'Short Urls',
                        translateKey: 'nav.appsCommuncication.urlShortner',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsCommuncication.notification',
                        path: `${APP_PREFIX_PATH}/appsCommuncication/notification`,
                        title: 'Notification Config',
                        translateKey: 'nav.appsCommuncication.notification',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsCommuncication.manageTemplates',
                        path: `${APP_PREFIX_PATH}/appsCommuncication/templates`,
                        title: 'WhatsApp Templates',
                        translateKey: 'nav.appsCommuncication.manageTemplates',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsCommuncication.whatsAppMessage',
                        path: `${APP_PREFIX_PATH}/appsCommuncication/whatsAppMessage`,
                        title: 'WhatsApp Message Sender',
                        translateKey: 'nav.appsCommuncication.whatsAppMessage',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsCommuncication.events',
                        path: `${APP_PREFIX_PATH}/appsCommuncication/events`,
                        title: 'Events',
                        translateKey: 'nav.appsCommuncication.events',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    // {
                    //     key: 'appscreatorPost.uploadPost',
                    //     path: `${APP_PREFIX_PATH}/uploadPost`,
                    //     title: 'Upload Post',
                    //     translateKey: 'nav.appsOrgManagement.uploadPost',
                    //     icon: '',
                    //     type: NAV_ITEM_TYPE_ITEM,
                    //     authority: [ADMIN, USER],
                    //     subMenu: [],
                    // },
                ],
            },

            // ///////////////////////////

            {
                key: 'apps.tryAndBuy',
                path: '',
                title: 'SLIKK Logistic',
                translateKey: 'nav.appstryAndBuy.tryAndBuy',
                icon: 'delivery',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'appstryAndBuy.riders',
                        path: `${APP_PREFIX_PATH}/riders`,
                        title: 'Riders',
                        translateKey: 'nav.appstryAndBuy.tryAndBuy',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appstryAndBuy.riderZone',
                        path: `${APP_PREFIX_PATH}/riderZone`,
                        title: 'Rider Zone',
                        translateKey: 'nav.appstryAndBuy.tryAndBuy',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appstryAndBuy.taskTracking',
                        path: `${APP_PREFIX_PATH}/tryAndBuy/taskTracking`,
                        title: 'Forward Task ',
                        translateKey: 'nav.appstryAndBuy.tryAndBuy',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appstryAndBuy.reverseTracking',
                        path: `${APP_PREFIX_PATH}/tryAndBuy/reverseTracking`,
                        title: 'Reverse Task ',
                        translateKey: 'nav.appstryAndBuy.tryAndBuy',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appstryAndBuy.riderTracking',
                        path: `${APP_PREFIX_PATH}/tryAndBuy/riderTracking`,
                        title: 'Rider Tracking',
                        translateKey: 'nav.appstryAndBuy.tryAndBuy',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },

                    {
                        key: 'appstryAndBuy.reverseTrip',
                        path: `${APP_PREFIX_PATH}/reverseTrip`,
                        title: 'Reverse Trip',
                        translateKey: 'nav.appstryAndBuy.tryAndBuy',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appstryAndBuy.picker',
                        path: `${APP_PREFIX_PATH}/pickerBoard`,
                        title: 'Picker',
                        translateKey: 'nav.appstryAndBuy.tryAndBuy',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appstryAndBuy.cashCollection',
                        path: `${APP_PREFIX_PATH}/cashCollection`,
                        title: 'Cash Recon',
                        translateKey: 'nav.appstryAndBuy.cashCollection',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                ],
            },

            {
                key: 'apps.analytics',
                path: '',
                title: 'Analytics',
                translateKey: 'nav.appsAnalytics.analytics',
                icon: 'analytics',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'appsAnalytics.orders',
                        path: `${APP_PREFIX_PATH}/analytics/orders`,
                        title: 'Orders',
                        translateKey: 'nav.appsAnalytics.orders',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsAnalytics.returns',
                        path: `${APP_PREFIX_PATH}/analytics/returns`,
                        title: 'Returns',
                        translateKey: 'nav.appsAnalytics.returns',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsAnalytics.userAnalytics',
                        path: `${APP_PREFIX_PATH}/analytics/userAnalytics`,
                        title: 'Users',
                        translateKey: 'nav.appsAnalytics.userAnalytics',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsAnalytics.remitance',
                        path: `${APP_PREFIX_PATH}/analytics/remitance`,
                        title: 'Remittance',
                        translateKey: 'nav.appsAnalytics.remitance',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsAnalytics.masterRemitance',
                        path: `${APP_PREFIX_PATH}/analytics/masterRemitance`,
                        title: 'Master Remitance',
                        translateKey: 'nav.appsAnalytics.masterRemitance',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsAnalytics.reports',
                        path: `${APP_PREFIX_PATH}/analytics/reports`,
                        title: 'Reports',
                        translateKey: 'nav.appsAnalytics.reports',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsAnalytics.monthlyReport',
                        path: `${APP_PREFIX_PATH}/analytics/monthlyReport`,
                        title: 'Monthly Reports',
                        translateKey: 'nav.appsAnalytics.monthlyReport',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },

                    // {
                    //     key: 'appsAnalytics.riderTracking',
                    //     path: `${APP_PREFIX_PATH}/tryAndBuy/riderTracking`,
                    //     title: 'Rider Tracking',
                    //     translateKey: 'nav.appstryAndBuy.tryAndBuy',
                    //     icon: '',
                    //     type: NAV_ITEM_TYPE_ITEM,
                    //     authority: [ADMIN, USER],
                    //     subMenu: [],
                    // },
                ],
            },

            {
                key: 'apps.configuration',
                path: '',
                title: 'Configuration',
                translateKey: 'nav.appsConfiguration.configuration',
                icon: 'config',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'appsConfiguration.configurations',
                        path: `${APP_PREFIX_PATH}/configurations`,
                        title: 'Configurations',
                        translateKey: 'nav.appsConfiguration.configurations',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsConfiguration.storeConfigurations',
                        path: `${APP_PREFIX_PATH}/storeConfigurations`,
                        title: 'Store Configurations',
                        translateKey: 'nav.appsConfiguration.storeConfigurations',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsConfiguration.reportConfigurations',
                        path: `${APP_PREFIX_PATH}/reportConfigurations`,
                        title: 'Report Configurations',
                        translateKey: 'nav.appsConfiguration.reportConfigurations',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsConfiguration.loyality',
                        path: `${APP_PREFIX_PATH}/loyality`,
                        title: 'Loyalty',
                        translateKey: 'nav.appsConfiguration.loyality',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    // {
                    //     key: 'appsConfiguration.scrapper',
                    //     path: `${APP_PREFIX_PATH}/scrapper`,
                    //     title: 'scrapper',
                    //     translateKey: 'nav.appsConfiguration.scrapper',
                    //     icon: '',
                    //     type: NAV_ITEM_TYPE_ITEM,
                    //     authority: [ADMIN, USER],
                    //     subMenu: [],
                    // },
                    // {
                    //     key: 'appsConfiguration.tasksAndSchedular',
                    //     path: `${APP_PREFIX_PATH}/tasksAndSchedular`,
                    //     title: 'Tasks&Schedular',
                    //     translateKey: 'nav.appsConfiguration.tasksAndSchedular',
                    //     icon: '',
                    //     type: NAV_ITEM_TYPE_ITEM,
                    //     authority: [ADMIN, USER],
                    //     subMenu: [],
                    // },
                ],
            },
        ],
    },
]

export default appsNavigationConfig
