import { APP_PREFIX_PATH } from '@/constants/route.constant'
import { NAV_ITEM_TYPE_TITLE, NAV_ITEM_TYPE_COLLAPSE, NAV_ITEM_TYPE_ITEM } from '@/constants/navigation.constant'
import { ADMIN, USER } from '@/constants/roles.constant'
import type { NavigationTree } from '@/@types/navigation'

const appsNavigationConfig: NavigationTree[] = [
    {
        key: 'apps',
        path: '',
        title: 'APPS',
        translateKey: 'nav.apps',
        icon: 'apps',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [ADMIN, USER],
        subMenu: [
            {
                key: 'apps.homePage',
                path: `${APP_PREFIX_PATH}/homePage`,
                title: 'Home',
                translateKey: 'nav.appsHomepage.homePage',
                icon: 'home',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [],
            },
            {
                key: 'apps.orderManagement',
                path: '',
                title: 'Order Management',
                translateKey: 'nav.appsOrderManagement.orderManagement',
                icon: 'sales',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'appsOrderManagement.orderList',
                        path: `${APP_PREFIX_PATH}/orders`,
                        title: 'New Orders',
                        translateKey: 'nav.appsOrderManagement.orderList',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsOrderManagement.returnOrderList',
                        path: `${APP_PREFIX_PATH}/returnOrders`,
                        title: 'Return Orders',
                        translateKey: 'nav.appsOrderManagement.returnOrderList',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsOrderManagement.deliveryOrders',
                        path: `${APP_PREFIX_PATH}/deliveryOrders`,
                        title: 'Forward Delivery',
                        translateKey: 'nav.appsOrderManagement.deliveryOrders',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsOrderManagement.reverseDelivery',
                        path: `${APP_PREFIX_PATH}/reverseDelivery`,
                        title: 'Reverse Delivery',
                        translateKey: 'nav.appsOrderManagement.reverseDelivery',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsOrderManagement.skuOrderHistory',
                        path: `${APP_PREFIX_PATH}/skuOrderHistory`,
                        title: 'Sku Order History',
                        translateKey: 'nav.appsOrderManagement.skuOrderHistory',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                ],
            },

            // Inventory Management.................................................
            {
                key: 'apps.inventoryManagement',
                path: '',
                title: 'Inventory Management',
                translateKey: 'nav.appsInventoryManagement.inventoryManagement',
                icon: 'inventory',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'appsInventoryManagement.inwards',
                        path: `${APP_PREFIX_PATH}/goods/received`,
                        title: 'Inwards',
                        translateKey: 'nav.appsInventoryManagement.inwards',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsInventoryManagement.quality_check',
                        path: `${APP_PREFIX_PATH}/goods/qualitycheck`,
                        title: 'Quality Check',
                        translateKey: 'nav.appsInventoryManagement.quality_check',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsInventoryManagement.quality_checkList',
                        path: `${APP_PREFIX_PATH}/goods/qualitycheckList`,
                        title: 'Quality Check List',
                        translateKey: 'nav.appsInventoryManagement.quality_check',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsInventoryManagement.stock_overview',
                        path: `${APP_PREFIX_PATH}/stockOverview`,
                        title: 'Stock Overview',
                        translateKey: 'nav.appsInventoryManagement.stock_overview',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                ],
            },

            //......................................................................

            // Vendor management.....................................................................

            {
                key: 'apps.vendorManagement',
                path: '',
                title: 'Brand Dashboard',
                translateKey: 'nav.appsVendorManagement.vendorManagement',
                icon: 'brand',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'appsVendorManagement.businessDetails',
                        path: `${APP_PREFIX_PATH}/vendor/Details`,
                        title: 'Business Details',
                        translateKey: 'nav.appsVendorManagement.businessDetails',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsVendorManagement.salesOverview',
                        path: `${APP_PREFIX_PATH}/vendor/sales`,
                        title: 'Sales Overview',
                        translateKey: 'nav.appsVendorManagement.salesOverview',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsVendorManagement.users',
                        path: `${APP_PREFIX_PATH}/vendor/users`,
                        title: 'Users',
                        translateKey: 'nav.appsInventoryManagement.users',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsVendorManagement.catalog',
                        path: `${APP_PREFIX_PATH}/vendor/catalog`,
                        title: 'Catalog Overview',
                        translateKey: 'nav.appsInventoryManagement.catalog',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsVendorManagement.stockOverview',
                        path: `${APP_PREFIX_PATH}/vendor/stock`,
                        title: 'Stock Overview',
                        translateKey: 'nav.appsVendorManagement.stockOverview',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsVendorManagement.orders',
                        path: `${APP_PREFIX_PATH}/vendor/orders`,
                        title: 'Orders',
                        translateKey: 'nav.appsVendorManagement.orders',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },

                    {
                        key: 'appsVendorManagement.returns',
                        path: `${APP_PREFIX_PATH}/vendor/returns`,
                        title: 'Returns',
                        translateKey: 'nav.appsVendorManagement.returns',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsVendorManagement.accounts',
                        path: `${APP_PREFIX_PATH}/vendor/accounts`,
                        title: 'Accounting Details',
                        translateKey: 'nav.appsVendorManagement.accounts',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                ],
            },

            //.......................................................................................

            {
                key: 'apps.category',
                path: '',
                title: 'Catalog Management',
                translateKey: 'nav.appsCategory.category',
                icon: 'category',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'appsCategory.uploadCatalog',
                        path: `${APP_PREFIX_PATH}/catalog/upload`,
                        title: 'Catalog Upload',
                        translateKey: 'nav.appsCategory.uploadCatalog',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsCategory.products',
                        path: `${APP_PREFIX_PATH}/catalog/products`,
                        title: 'Products',
                        translateKey: 'nav.appsCategory.products',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsCategory.division',
                        path: `${APP_PREFIX_PATH}/category/division`,
                        title: 'Division',
                        translateKey: 'nav.appsCategory.division',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsCategory.category',
                        path: `${APP_PREFIX_PATH}/category/category`,
                        title: 'Category',
                        translateKey: 'nav.appsCategory.category',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsCategory.subCategory',
                        path: `${APP_PREFIX_PATH}/category/subCategory`,
                        title: 'Sub Category',
                        translateKey: 'nav.appsCategory.subCategory',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsCategory.productType',
                        path: `${APP_PREFIX_PATH}/category/productType`,
                        title: 'Product Type',
                        translateKey: 'nav.appsCategory.productType',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsCategory.brand',
                        path: `${APP_PREFIX_PATH}/category/brand`,
                        title: 'Brand',
                        translateKey: 'nav.appsCategory.brand',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsCategory.productFeedback',
                        path: `${APP_PREFIX_PATH}/category/productFeedback`,
                        title: 'Product Feedback',
                        translateKey: 'nav.appsCategory.productFeedback',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsCategory.uploader',
                        path: `${APP_PREFIX_PATH}/category/uploader`,
                        title: 'Uploader',
                        translateKey: 'nav.appsCategory.productFeedback',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                ],
            },
            //..........................................................................................................
            {
                key: 'apps.OrgManagement',
                path: '',
                title: 'Organization Management',
                translateKey: 'nav.appsOrgManagement.OrgManagement',
                icon: 'org',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'appsOrgManagement.sellers',
                        path: `${APP_PREFIX_PATH}/sellers`,
                        title: 'Sellers',
                        translateKey: 'nav.appsOrgManagement.sellers',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsOrgManagement.stores',
                        path: `${APP_PREFIX_PATH}/stores`,
                        title: 'Fullfillment Center',
                        translateKey: 'nav.appsOrgManagement.stores',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsOrgManagement.users',
                        path: `${APP_PREFIX_PATH}/users`,
                        title: 'Users',
                        translateKey: 'nav.appsOrgManagement.users',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsOrgManagement.accessManagement',
                        path: `${APP_PREFIX_PATH}/accessManagement`,
                        title: 'Access Management',
                        translateKey: 'nav.appsOrgManagement.accessManagement',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                ],
            },

            // Creator Post.......................................................................................................

            {
                key: 'apps.creatorPost',
                path: `${APP_PREFIX_PATH}/userposts/approval`,
                title: 'Creator Posts',
                translateKey: 'nav.apps.creatorPost.creatorPost',
                icon: 'reels',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'appscreatorPost.postApproval',
                        path: `${APP_PREFIX_PATH}/postApproval`,
                        title: 'Post Approval',
                        translateKey: 'nav.appsOrgManagement.postApproval',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appscreatorPost.uploadPost',
                        path: `${APP_PREFIX_PATH}/uploadPost`,
                        title: 'Upload Post',
                        translateKey: 'nav.appsOrgManagement.uploadPost',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                ],
            },

            // .............................................................................................................

            {
                key: 'apps.appSettings',
                path: '',
                title: 'App Settings',
                translateKey: 'nav.appsAppSettings.appSettings',
                icon: 'appsettings',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'appsAppSettings.coupons',
                        path: `${APP_PREFIX_PATH}/appSettings/coupons`,
                        title: 'Coupons',
                        translateKey: 'nav.appsAppSettings.coupons',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsAppSettings.banners',
                        path: `${APP_PREFIX_PATH}/appSettings/banners`,
                        title: 'Banners',
                        translateKey: 'nav.appsAppSettings.banners',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsAppSettings.pageSettings',
                        path: `${APP_PREFIX_PATH}/appSettings/pageSettings`,
                        title: 'Page Settings',
                        translateKey: 'nav.appsAppSettings.pageSettings',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsAppSettings.policies',
                        path: `${APP_PREFIX_PATH}/appSettings/policies`,
                        title: 'Policies',
                        translateKey: 'nav.appsAppSettings.policies',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsAppSettings.seoSettings',
                        path: `${APP_PREFIX_PATH}/appSettings/seoSettings`,
                        title: 'Seo Settings',
                        translateKey: 'nav.appsAppSettings.seoSettings',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },

                    // {
                    //     key: 'appsAppSettings.groups',
                    //     path: `${APP_PREFIX_PATH}/appSettings/groups`,
                    //     title: 'Groups',
                    //     translateKey: 'nav.appsAppSettings.groups',
                    //     icon: '',
                    //     type: NAV_ITEM_TYPE_ITEM,
                    //     authority: [ADMIN, USER],
                    //     subMenu: [],
                    // },
                ],
            },

            {
                key: 'apps.communcication',
                path: `${APP_PREFIX_PATH}/communication`,
                title: 'Communciation',
                translateKey: 'nav.appsCommuncication.communcication',
                icon: 'communication',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'appsCommuncication.groups',
                        path: `${APP_PREFIX_PATH}/appsCommuncication/groups`,
                        title: 'Groups',
                        translateKey: 'nav.appsCommuncication.groups',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsCommuncication.sendNotification',
                        path: `${APP_PREFIX_PATH}/appsCommuncication/sendNotification`,
                        title: 'Send Notification',
                        translateKey: 'nav.appsCommuncication.sendNotification',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsCommuncication.urlShortner',
                        path: `${APP_PREFIX_PATH}/appsCommuncication/urlShortner`,
                        title: 'Short Urls',
                        translateKey: 'nav.appsCommuncication.urlShortner',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsCommuncication.notification',
                        path: `${APP_PREFIX_PATH}/appsCommuncication/notification`,
                        title: 'Notification Config',
                        translateKey: 'nav.appsCommuncication.notification',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    // {
                    //     key: 'appscreatorPost.uploadPost',
                    //     path: `${APP_PREFIX_PATH}/uploadPost`,
                    //     title: 'Upload Post',
                    //     translateKey: 'nav.appsOrgManagement.uploadPost',
                    //     icon: '',
                    //     type: NAV_ITEM_TYPE_ITEM,
                    //     authority: [ADMIN, USER],
                    //     subMenu: [],
                    // },
                ],
            },

            // ///////////////////////////

            {
                key: 'apps.tryAndBuy',
                path: '',
                title: 'SLIKK Logistic',
                translateKey: 'nav.appstryAndBuy.tryAndBuy',
                icon: 'delivery',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'appstryAndBuy.taskTracking',
                        path: `${APP_PREFIX_PATH}/tryAndBuy/taskTracking`,
                        title: 'Forward Task ',
                        translateKey: 'nav.appstryAndBuy.tryAndBuy',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appstryAndBuy.reverseTracking',
                        path: `${APP_PREFIX_PATH}/tryAndBuy/reverseTracking`,
                        title: 'Reverse Task ',
                        translateKey: 'nav.appstryAndBuy.tryAndBuy',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appstryAndBuy.riderTracking',
                        path: `${APP_PREFIX_PATH}/tryAndBuy/riderTracking`,
                        title: 'Rider Tracking',
                        translateKey: 'nav.appstryAndBuy.tryAndBuy',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },

                    {
                        key: 'appstryAndBuy.reverseTrip',
                        path: `${APP_PREFIX_PATH}/reverseTrip`,
                        title: 'Reverse Trip',
                        translateKey: 'nav.appstryAndBuy.tryAndBuy',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                ],
            },

            {
                key: 'apps.analytics',
                path: '',
                title: 'Analytics',
                translateKey: 'nav.appsAnalytics.analytics',
                icon: 'analytics',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'appsAnalytics.orders',
                        path: `${APP_PREFIX_PATH}/analytics/orders`,
                        title: 'Orders',
                        translateKey: 'nav.appsAnalytics.orders',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsAnalytics.returns',
                        path: `${APP_PREFIX_PATH}/analytics/returns`,
                        title: 'Returns',
                        translateKey: 'nav.appsAnalytics.returns',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsAnalytics.userAnalytics',
                        path: `${APP_PREFIX_PATH}/analytics/userAnalytics`,
                        title: 'Users',
                        translateKey: 'nav.appsAnalytics.userAnalytics',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsAnalytics.remitance',
                        path: `${APP_PREFIX_PATH}/analytics/remitance`,
                        title: 'Remittance',
                        translateKey: 'nav.appsAnalytics.remitance',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsAnalytics.masterRemitance',
                        path: `${APP_PREFIX_PATH}/analytics/masterRemitance`,
                        title: 'Master Remitance',
                        translateKey: 'nav.appsAnalytics.masterRemitance',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsAnalytics.reports',
                        path: `${APP_PREFIX_PATH}/analytics/reports`,
                        title: 'Reports',
                        translateKey: 'nav.appsAnalytics.reports',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsAnalytics.monthlyReport',
                        path: `${APP_PREFIX_PATH}/analytics/monthlyReport`,
                        title: 'Monthly Reports',
                        translateKey: 'nav.appsAnalytics.monthlyReport',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },

                    // {
                    //     key: 'appsAnalytics.riderTracking',
                    //     path: `${APP_PREFIX_PATH}/tryAndBuy/riderTracking`,
                    //     title: 'Rider Tracking',
                    //     translateKey: 'nav.appstryAndBuy.tryAndBuy',
                    //     icon: '',
                    //     type: NAV_ITEM_TYPE_ITEM,
                    //     authority: [ADMIN, USER],
                    //     subMenu: [],
                    // },
                ],
            },

            {
                key: 'apps.configuration',
                path: '',
                title: 'Configuration',
                translateKey: 'nav.appsConfiguration.configuration',
                icon: 'config',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'appsConfiguration.configurations',
                        path: `${APP_PREFIX_PATH}/configurations`,
                        title: 'Configurations',
                        translateKey: 'nav.appsConfiguration.configurations',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsConfiguration.reportConfigurations',
                        path: `${APP_PREFIX_PATH}/reportConfigurations`,
                        title: 'Report Configurations',
                        translateKey: 'nav.appsConfiguration.reportConfigurations',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsConfiguration.loyality',
                        path: `${APP_PREFIX_PATH}/loyality`,
                        title: 'Loyality',
                        translateKey: 'nav.appsConfiguration.loyality',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    // {
                    //     key: 'appsConfiguration.tasksAndSchedular',
                    //     path: `${APP_PREFIX_PATH}/tasksAndSchedular`,
                    //     title: 'Tasks&Schedular',
                    //     translateKey: 'nav.appsConfiguration.tasksAndSchedular',
                    //     icon: '',
                    //     type: NAV_ITEM_TYPE_ITEM,
                    //     authority: [ADMIN, USER],
                    //     subMenu: [],
                    // },
                ],
            },
        ],
    },
]

export default appsNavigationConfig
