import { APP_PREFIX_PATH } from '@/constants/route.constant'
import { NAV_ITEM_TYPE_TITLE, NAV_ITEM_TYPE_COLLAPSE, NAV_ITEM_TYPE_ITEM } from '@/constants/navigation.constant'
import { ADMIN, USER } from '@/constants/roles.constant'
import type { NavigationTree } from '@/@types/navigation'

const vendorNavigationConfig: NavigationTree[] = [
    {
        key: 'apps',
        path: '',
        title: '',
        translateKey: 'nav.apps',
        icon: 'apps',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [ADMIN, USER],
        subMenu: [
            // {
            //     key: 'appsVendorManagement.salesOverview',
            //     path: `${APP_PREFIX_PATH}/vendor/sales`,
            //     title: 'Sales Overview',
            //     translateKey: 'nav.appsVendorManagement.salesOverview',
            //     icon: 'sales',
            //     type: NAV_ITEM_TYPE_ITEM,
            //     authority: [ADMIN, USER],
            //     subMenu: []
            // },
            {
                key: 'appsVendorManagement.orders',
                path: `${APP_PREFIX_PATH}/vendor/orders`,
                title: 'Orders',
                translateKey: 'nav.appsVendorManagement.orders',
                icon: 'bill',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, USER],
                subMenu: [],
            },

            {
                key: 'appsVendorManagement.returns',
                path: `${APP_PREFIX_PATH}/vendor/returns`,
                title: 'Returns',
                translateKey: 'nav.appsVendorManagement.returns',
                icon: 'return',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, USER],
                subMenu: [],
            },
            {
                key: 'appsVendorManagement.catalog',
                path: `${APP_PREFIX_PATH}/vendor/catalog`,
                title: 'Catalog Overview',
                translateKey: 'nav.appsVendorManagement.catalog',
                icon: 'category',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, USER],
                subMenu: [],
            },
            {
                key: 'appsVendorManagement.stockOverview',
                path: `${APP_PREFIX_PATH}/vendor/stock`,
                title: 'Stock Overview',
                translateKey: 'nav.appsVendorManagement.stockOverview',
                icon: 'inventory',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, USER],
                subMenu: [],
            },
            {
                key: 'appsVendorManagement.businessDetails',
                path: `${APP_PREFIX_PATH}/vendor/details`,
                title: 'Brand Info',
                translateKey: 'nav.appsVendorManagement.businessDetails',
                icon: 'brand',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, USER],
                subMenu: [],
            },

            {
                key: 'appsVendorManagement.users',
                path: `${APP_PREFIX_PATH}/vendor/users`,
                title: 'Users',
                translateKey: 'nav.appsInventoryManagement.users',
                icon: 'users',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, USER],
                subMenu: [],
            },

            // {
            //     key: 'appsVendorManagement.accounts',
            //     path: `${APP_PREFIX_PATH}/vendor/accounts`,
            //     title: 'Accounting Details',
            //     translateKey: 'nav.appsVendorManagement.accounts',
            //     icon: 'note',
            //     type: NAV_ITEM_TYPE_ITEM,
            //     authority: [ADMIN, USER],
            //     subMenu: []
            // }
            // {
            //     key: 'apps.orderManagement',
            //     path: '',
            //     title: 'Order Management',
            //     translateKey: 'nav.appsOrderManagement.orderManagement',
            //     icon: 'sales',
            //     type: NAV_ITEM_TYPE_COLLAPSE,
            //     authority: [ADMIN, USER],
            //     subMenu: [
            //         {
            //             key: 'appsOrderManagement.orderList',
            //             path: `${APP_PREFIX_PATH}/orders`,
            //             title: 'New Orders',
            //             translateKey: 'nav.appsOrderManagement.orderList',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsOrderManagement.returnOrderList',
            //             path: `${APP_PREFIX_PATH}/returnOrders`,
            //             title: 'Return Orders',
            //             translateKey: 'nav.appsOrderManagement.returnOrderList',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsOrderManagement.deliveryOrders',
            //             path: `${APP_PREFIX_PATH}/deliveryOrders`,
            //             title: 'Delivery Orders',
            //             translateKey: 'nav.appsOrderManagement.deliveryOrders',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //     ],
            // },

            // // Inventory Management.................................................
            // {
            //     key: 'apps.inventoryManagement',
            //     path: '',
            //     title: 'Inventory Management',
            //     translateKey: 'nav.appsInventoryManagement.inventoryManagement',
            //     icon: 'inventory',
            //     type: NAV_ITEM_TYPE_COLLAPSE,
            //     authority: [ADMIN, USER],
            //     subMenu: [
            //         {
            //             key: 'appsInventoryManagement.inwards',
            //             path: `${APP_PREFIX_PATH}/goods/received`,
            //             title: 'Inwards',
            //             translateKey: 'nav.appsInventoryManagement.inwards',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsInventoryManagement.quality_check',
            //             path: `${APP_PREFIX_PATH}/goods/qualitycheck`,
            //             title: 'Quality Check',
            //             translateKey:
            //                 'nav.appsInventoryManagement.quality_check',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsInventoryManagement.quality_checkList',
            //             path: `${APP_PREFIX_PATH}/goods/qualitycheckList`,
            //             title: 'Quality Check List',
            //             translateKey:
            //                 'nav.appsInventoryManagement.quality_check',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsInventoryManagement.stock_overview',
            //             path: `${APP_PREFIX_PATH}/stockOverview`,
            //             title: 'Stock Overview',
            //             translateKey:
            //                 'nav.appsInventoryManagement.stock_overview',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //     ],
            // },

            //......................................................................

            // Vendor management.....................................................................

            // {
            //     key: 'apps.vendorManagement',
            //     path: '',
            //     title: 'Brand Dashboard',
            //     translateKey: 'nav.appsVendorManagement.vendorManagement',
            //     icon: 'brand',
            //     type: NAV_ITEM_TYPE_COLLAPSE,
            //     authority: [ADMIN, USER],
            //     subMenu: [

            //     ]
            // }

            //.......................................................................................

            // {
            //     key: 'apps.category',
            //     path: '',
            //     title: 'Catalog Management',
            //     translateKey: 'nav.appsCategory.category',
            //     icon: 'category',
            //     type: NAV_ITEM_TYPE_COLLAPSE,
            //     authority: [ADMIN, USER],
            //     subMenu: [
            //         {
            //             key: 'appsCategory.uploadCatalog',
            //             path: `${APP_PREFIX_PATH}/catalog/upload`,
            //             title: 'Catalog Upload',
            //             translateKey: 'nav.appsCategory.uploadCatalog',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsCategory.products',
            //             path: `${APP_PREFIX_PATH}/catalog/products`,
            //             title: 'Products',
            //             translateKey: 'nav.appsCategory.products',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsCategory.division',
            //             path: `${APP_PREFIX_PATH}/category/division`,
            //             title: 'Division',
            //             translateKey: 'nav.appsCategory.division',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsCategory.category',
            //             path: `${APP_PREFIX_PATH}/category/category`,
            //             title: 'Category',
            //             translateKey: 'nav.appsCategory.category',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsCategory.subCategory',
            //             path: `${APP_PREFIX_PATH}/category/subCategory`,
            //             title: 'Sub Category',
            //             translateKey: 'nav.appsCategory.subCategory',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsCategory.productType',
            //             path: `${APP_PREFIX_PATH}/category/productType`,
            //             title: 'Product Type',
            //             translateKey: 'nav.appsCategory.productType',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsCategory.brand',
            //             path: `${APP_PREFIX_PATH}/category/brand`,
            //             title: 'Brand',
            //             translateKey: 'nav.appsCategory.brand',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsCategory.productFeedback',
            //             path: `${APP_PREFIX_PATH}/category/productFeedback`,
            //             title: 'Product Feedback',
            //             translateKey: 'nav.appsCategory.productFeedback',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //     ],
            // },
            // //..........................................................................................................
            // {
            //     key: 'apps.OrgManagement',
            //     path: '',
            //     title: 'Organization Management',
            //     translateKey: 'nav.appsOrgManagement.OrgManagement',
            //     icon: 'org',
            //     type: NAV_ITEM_TYPE_COLLAPSE,
            //     authority: [ADMIN, USER],
            //     subMenu: [
            //         {
            //             key: 'appsOrgManagement.sellers',
            //             path: `${APP_PREFIX_PATH}/sellers`,
            //             title: 'Sellers',
            //             translateKey: 'nav.appsOrgManagement.sellers',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsOrgManagement.stores',
            //             path: `${APP_PREFIX_PATH}/stores`,
            //             title: 'Fullfillment Center',
            //             translateKey: 'nav.appsOrgManagement.stores',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsOrgManagement.users',
            //             path: `${APP_PREFIX_PATH}/users`,
            //             title: 'Users',
            //             translateKey: 'nav.appsOrgManagement.users',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //     ],
            // },

            // // Creator Post.......................................................................................................

            // {
            //     key: 'apps.creatorPost',
            //     path: `${APP_PREFIX_PATH}/userposts/approval`,
            //     title: 'Creator Posts',
            //     translateKey: 'nav.apps.creatorPost.creatorPost',
            //     icon: 'reels',
            //     type: NAV_ITEM_TYPE_COLLAPSE,
            //     authority: [ADMIN, USER],
            //     subMenu: [
            //         {
            //             key: 'appscreatorPost.postApproval',
            //             path: `${APP_PREFIX_PATH}/postApproval`,
            //             title: 'Post Approval',
            //             translateKey: 'nav.appsOrgManagement.postApproval',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appscreatorPost.uploadPost',
            //             path: `${APP_PREFIX_PATH}/uploadPost`,
            //             title: 'Upload Post',
            //             translateKey: 'nav.appsOrgManagement.uploadPost',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //     ],
            // },

            // // .............................................................................................................

            // {
            //     key: 'apps.appSettings',
            //     path: '',
            //     title: 'App Settings',
            //     translateKey: 'nav.appsAppSettings.appSettings',
            //     icon: 'appsettings',
            //     type: NAV_ITEM_TYPE_COLLAPSE,
            //     authority: [ADMIN, USER],
            //     subMenu: [
            //         {
            //             key: 'appsAppSettings.coupons',
            //             path: `${APP_PREFIX_PATH}/appSettings/coupons`,
            //             title: 'Coupons',
            //             translateKey: 'nav.appsAppSettings.coupons',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsAppSettings.banners',
            //             path: `${APP_PREFIX_PATH}/appSettings/banners`,
            //             title: 'Banners',
            //             translateKey: 'nav.appsAppSettings.banners',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsAppSettings.pageSettings',
            //             path: `${APP_PREFIX_PATH}/appSettings/pageSettings`,
            //             title: 'Page Settings',
            //             translateKey: 'nav.appsAppSettings.pageSettings',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsAppSettings.policies',
            //             path: `${APP_PREFIX_PATH}/appSettings/policies`,
            //             title: 'Policies',
            //             translateKey: 'nav.appsAppSettings.policies',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsAppSettings.seoSettings',
            //             path: `${APP_PREFIX_PATH}/appSettings/seoSettings`,
            //             title: 'Seo Settings',
            //             translateKey: 'nav.appsAppSettings.seoSettings',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //     ],
            // },

            // // ///////////////////////////

            // {
            //     key: 'apps.tryAndBuy',
            //     path: '',
            //     title: 'SLIKK Logistic',
            //     translateKey: 'nav.appstryAndBuy.tryAndBuy',
            //     icon: 'delivery',
            //     type: NAV_ITEM_TYPE_COLLAPSE,
            //     authority: [ADMIN, USER],
            //     subMenu: [
            //         {
            //             key: 'appstryAndBuy.taskTracking',
            //             path: `${APP_PREFIX_PATH}/tryAndBuy/taskTracking`,
            //             title: 'Task Tracking',
            //             translateKey: 'nav.appstryAndBuy.tryAndBuy',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appstryAndBuy.riderTracking',
            //             path: `${APP_PREFIX_PATH}/tryAndBuy/riderTracking`,
            //             title: 'Rider Tracking',
            //             translateKey: 'nav.appstryAndBuy.tryAndBuy',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //     ],
            // },

            // ..............................................................................................................

            // {
            //     key: 'apps.project',
            //     path: '',
            //     title: 'Project',
            //     translateKey: 'nav.appsProject.project',
            //     icon: 'project',
            //     type: NAV_ITEM_TYPE_COLLAPSE,
            //     authority: [ADMIN, USER],
            //     subMenu: [
            //         {
            //             key: 'appsProject.dashboard',
            //             path: `${APP_PREFIX_PATH}/project/dashboard`,
            //             title: 'Dashboard',
            //             translateKey: 'nav.appsProject.dashboard',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsProject.projectList',
            //             path: `${APP_PREFIX_PATH}/project/project-list`,
            //             title: 'Project List',
            //             translateKey: 'nav.appsProject.projectList',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsProject.scrumBoard',
            //             path: `${APP_PREFIX_PATH}/project/scrum-board`,
            //             title: 'Scrum Board',
            //             translateKey: 'nav.appsProject.scrumBoard',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsProject.issue',
            //             path: `${APP_PREFIX_PATH}/project/issue`,
            //             title: 'Issue',
            //             translateKey: 'nav.appsProject.issue',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //     ],
            // },
            // {
            //     key: 'apps.crm',
            //     path: '',
            //     title: 'CRM',
            //     translateKey: 'nav.appsCrm.crm',
            //     icon: 'crm',
            //     type: NAV_ITEM_TYPE_COLLAPSE,
            //     authority: [ADMIN, USER],
            //     subMenu: [
            //         {
            //             key: 'appsCrm.dashboard',
            //             path: `${APP_PREFIX_PATH}/crm/dashboard`,
            //             title: 'Dashboard',
            //             translateKey: 'nav.appsCrm.dashboard',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsCrm.calendar',
            //             path: `${APP_PREFIX_PATH}/crm/calendar`,
            //             title: 'Calendar',
            //             translateKey: 'nav.appsCrm.calendar',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsCrm.customers',
            //             path: `${APP_PREFIX_PATH}/crm/customers`,
            //             title: 'Customers',
            //             translateKey: 'nav.appsCrm.customers',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsCrm.customerDetails',
            //             path: `${APP_PREFIX_PATH}/crm/customer-details?id=8`,
            //             title: 'Customer Details',
            //             translateKey: 'nav.appsCrm.customerDetails',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsCrm.mail',
            //             path: `${APP_PREFIX_PATH}/crm/mail`,
            //             title: 'Mail',
            //             translateKey: 'nav.appsCrm.mail',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //     ],
            // },
            // {
            //     key: 'apps.sales',
            //     path: '',
            //     title: 'Sales',
            //     translateKey: 'nav.appsSales.sales',
            //     icon: 'sales',
            //     type: NAV_ITEM_TYPE_COLLAPSE,
            //     authority: [ADMIN, USER],
            //     subMenu: [
            //         {
            //             key: 'appsSales.dashboard',
            //             path: `${APP_PREFIX_PATH}/sales/dashboard`,
            //             title: 'Dashboard',
            //             translateKey: 'nav.appsSales.dashboard',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsSales.productList',
            //             path: `${APP_PREFIX_PATH}/sales/product-list`,
            //             title: 'Product List',
            //             translateKey: 'nav.appsSales.productList',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsSales.productEdit',
            //             path: `${APP_PREFIX_PATH}/sales/product-edit/12`,
            //             title: 'Product Edit',
            //             translateKey: 'nav.appsSales.productEdit',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsSales.productNew',
            //             path: `${APP_PREFIX_PATH}/sales/product-new`,
            //             title: 'New Product',
            //             translateKey: 'nav.appsSales.productNew',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },

            //         {
            //             key: 'appsSales.orderDetails',
            //             path: `${APP_PREFIX_PATH}/sales/order-details/95954`,
            //             title: 'Order Details',
            //             translateKey: 'nav.appsSales.orderDetails',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //     ],
            // },
            // {
            //     key: 'apps.crypto',
            //     path: '',
            //     title: 'Crypto',
            //     translateKey: 'nav.appsCrypto.crypto',
            //     icon: 'crypto',
            //     type: NAV_ITEM_TYPE_COLLAPSE,
            //     authority: [ADMIN, USER],
            //     subMenu: [
            //         {
            //             key: 'appsCrypto.dashboard',
            //             path: `${APP_PREFIX_PATH}/crypto/dashboard`,
            //             title: 'Dashboard',
            //             translateKey: 'nav.appsCrypto.dashboard',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsCrypto.portfolio',
            //             path: `${APP_PREFIX_PATH}/crypto/portfolio`,
            //             title: 'Portfolio',
            //             translateKey: 'nav.appsCrypto.portfolio',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsCrypto.market',
            //             path: `${APP_PREFIX_PATH}/crypto/market`,
            //             title: 'Market',
            //             translateKey: 'nav.appsCrypto.market',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsCrypto.wallets',
            //             path: `${APP_PREFIX_PATH}/crypto/wallets`,
            //             title: 'Wallets',
            //             translateKey: 'nav.appsCrypto.wallets',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //     ],
            // },
            // {
            //     key: 'apps.knowledgeBase',
            //     path: '',
            //     title: 'Knowledge Base',
            //     translateKey: 'nav.appsknowledgeBase.knowledgeBase',
            //     icon: 'knowledgeBase',
            //     type: NAV_ITEM_TYPE_COLLAPSE,
            //     authority: [ADMIN, USER],
            //     subMenu: [
            //         {
            //             key: 'appsknowledgeBase.helpCenter',
            //             path: `${APP_PREFIX_PATH}/knowledge-base/help-center`,
            //             title: 'Help Center',
            //             translateKey: 'nav.appsknowledgeBase.helpCenter',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsknowledgeBase.article',
            //             path: `${APP_PREFIX_PATH}/knowledge-base/article?id=rZjCbSyae5`,
            //             title: 'Article',
            //             translateKey: 'nav.appsknowledgeBase.article',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsknowledgeBase.manageArticles',
            //             path: `${APP_PREFIX_PATH}/knowledge-base/manage-articles`,
            //             title: 'Manage Articles',
            //             translateKey: 'nav.appsknowledgeBase.manageArticles',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsknowledgeBase.editArticle',
            //             path: `${APP_PREFIX_PATH}/knowledge-base/edit-article?id=rZjCbSyae5&categoryLabel=Survey&categoryValue=survey`,
            //             title: 'Edit Article',
            //             translateKey: 'nav.appsknowledgeBase.editArticle',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //     ],
            // },
            // {
            //     key: 'apps.account',
            //     path: '',
            //     title: 'Account',
            //     translateKey: 'nav.appsAccount.account',
            //     icon: 'account',
            //     type: NAV_ITEM_TYPE_COLLAPSE,
            //     authority: [ADMIN, USER],
            //     subMenu: [
            //         {
            //             key: 'appsAccount.settings',
            //             path: `${APP_PREFIX_PATH}/account/settings/profile`,
            //             title: 'Settings',
            //             translateKey: 'nav.appsAccount.settings',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsAccount.invoice',
            //             path: `${APP_PREFIX_PATH}/account/invoice/36223`,
            //             title: 'Invoice',
            //             translateKey: 'nav.appsAccount.invoice',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsAccount.activityLog',
            //             path: `${APP_PREFIX_PATH}/account/activity-log`,
            //             title: 'Activity Log',
            //             translateKey: 'nav.appsAccount.activityLog',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsAccount.kycForm',
            //             path: `${APP_PREFIX_PATH}/account/kyc-form`,
            //             title: 'KYC Form',
            //             translateKey: 'nav.appsAccount.kycForm',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //     ],
            // },
        ],
    },
]

export default vendorNavigationConfig
