import Input from '@/components/ui/Input'

export const SELLING_FORM = [
    {
        label: 'Registered Name',
        classname: 'col-span-1 w-full',
        type: 'text',
        name: 'registered_name',
        placeholder: 'Place your Registered Name',
        component: { Input },
        status: 'registered_name',
    },
    {
        label: 'Name',
        classname: 'col-span-1 w-full',
        type: 'text',
        name: 'name',
        placeholder: 'Place your Brand Name',
        component: { Input },
        status: 'name',
    },
    {
        label: 'Seller Code',
        classname: 'col-span-1 w-full',
        type: 'text',
        name: 'code',
        placeholder: 'Enter Unique Seller code',
        component: { Input },
        status: 'code',
    },
    {
        label: 'GSTIN',
        classname: 'col-span-1 w-full',
        type: 'text',
        name: 'gstin',
        placeholder: 'Place your GSTIN',
        component: { Input },
        status: 'gstin',
    },
    {
        label: 'CIN',
        classname: 'col-span-1 w-full',
        type: 'text',
        name: 'cin',
        placeholder: 'Place your CIN',
        component: { Input },
        status: 'cin',
    },
    {
        label: 'Address',
        classname: 'col-span-1 w-full',
        type: 'text',
        name: 'address',
        placeholder: 'Place your Address',
        component: { Input },
        status: 'address',
    },
    {
        label: 'Revenue Share Percent',
        classname: 'col-span-1 w-full',
        type: 'text',
        name: 'revenue_share',
        placeholder: 'Place your Revenue Share',
        component: { Input },
        status: 'revenue_share',
    },
    {
        label: 'Handling Charges Per SKU',
        classname: 'col-span-1 w-full',
        type: 'text',
        name: 'handling_charges_per_order',
        placeholder: 'Confirm your Charges',
        component: { Input },
        status: 'handling_charges_per_order',
    },
    {
        label: 'Warehouse Charges Per SKU',
        classname: 'col-span-1 w-full',
        type: 'text',
        name: 'warehouse_charge_per_sku',
        placeholder: 'Place Warehouse Charges',
        component: { Input },
        status: 'warehouse_charge_per_sku',
    },
    {
        label: 'Damage Charges Per SKU',
        classname: 'col-span-1 w-full',
        type: 'text',
        name: 'damages_per_sku',
        placeholder: 'Place your Damage Charges',
        component: { Input },
        status: 'damages_per_sku',
    },
    {
        label: 'Removal Fee Per SKU',
        classname: 'col-span-1 w-full',
        type: 'text',
        name: 'removal_fee_per_sku',
        placeholder: 'Place your Removal Fee',
        component: { Input },
        status: 'removal_fee_per_sku',
    },
]

export const POC_FORM = [
    {
        label: 'POC Name',
        classname: 'col-span-1 w-full',
        type: 'text',
        name: 'poc',
        placeholder: 'Place your POC',
        component: { Input },
        status: 'poc',
    },
    {
        label: 'POC Email',
        classname: 'col-span-1 w-full',
        type: 'text',
        name: 'poc_email',
        placeholder: 'Place your POC EMAIL',
        component: { Input },
        status: 'poc_email',
    },
    {
        label: 'Mobile Number',
        classname: 'col-span-1 w-full',
        type: 'text',
        name: 'contact_number',
        placeholder: 'Place your Contact Number',
        component: { Input },
        status: 'contact_number',
    },
    {
        label: 'Alternate Contact Number',
        classname: 'col-span-1 w-full',
        type: 'text',
        name: 'alternate_contact_number',
        placeholder: 'Place your Alternate Contact Number',
        component: { Input },
        status: 'alternate_contact_number',
    },
]

export const ACCOUNT_FORM = [
    {
        label: 'Account Number',
        classname: 'col-span-1 w-full',
        type: 'text',
        name: 'account_number',
        placeholder: 'Place your Account Number',
        component: { Input },
        status: 'account_number',
    },
    {
        label: 'Confirm Account Number',
        classname: 'col-span-1 w-full',
        type: 'text',
        name: 'confirm',
        placeholder: 'Confirm your Account Number',
        component: { Input },
        status: 'confirm',
    },
    {
        label: 'Account Holder Name',
        classname: 'col-span-1 w-full',
        type: 'text',
        name: 'account_holder_name',
        placeholder: 'Place Account Holder Name',
        component: { Input },
        status: 'account_holder_name',
    },
    {
        label: 'Bank Name',
        classname: 'col-span-1 w-full',
        type: 'text',
        name: 'bank_name',
        placeholder: 'Place your Bank Name',
        component: { Input },
        status: 'bank_name',
    },
    {
        label: 'IFSC',
        classname: 'col-span-1 w-full',
        type: 'text',
        name: 'ifsc',
        placeholder: 'Place your IFSC',
        component: { Input },
        status: 'ifsc',
    },
]
