type Product = {
    company: number
    brand_name: string
    name: string
    description: string
    about: string
    benefits: string
    includes: string
    other_product_info: string
    variant_type: string
    variant_id: string
    tax_rate: number
    mrp: number
    sp: number
    barcode: string
    hsn: string
    sku: string
    usage: string
    imported_by: string
    shelf_life: number
    height: number
    width: number
    depth: number
    video_link: string
    video: File[]
    minimum_quantity: number
    reserve_quantity: number
    Status: string
    images: string
    image: File[]
    color_code: File[]
    category_name: string
    is_premium: boolean
    is_try_and_buy: boolean
    is_returnable: boolean
    sub_category_name: string
    product_type_name: string
    division_name: string
    Color: string
    ColourShadeName: string
    SkinType: string
    Formulation: string
    HairType: string
    gender: string
    Finish: string
    skintone: string
    Coverage: string
    sunprotection: string
    WeightVolumeUnitOfMeasure: string
    Concious: string
    productHexCode: string
    packSize: string
    productSize: string
    ingrediants: string
    vegnonveg: string
    ingrediantsPreferences: string
    concern: string
    recommendationfor: string
    scenttopnotes: string
    scentheartnotes: string
    scentbasenotes: string
    origincountry: string
    color_code_link: string
}

export default Product
