/* eslint-disable @typescript-eslint/no-explicit-any */
// Helper function to get initial values
export const InitialValues = (productData: any, segmentOptions: string[] | undefined) => ({
    domains: segmentOptions,
    company: productData?.company,
    brand_name: productData?.brand,
    name: productData?.name,
    description: productData?.description,
    about: productData?.about,
    benefits: productData?.benefits,
    includes: productData?.includes,
    other_product_info: productData?.other_product_info,
    variant_type: productData?.variant_type,
    variant_id: productData?.variant_id,
    tax_rate: productData?.tax_rate,
    mrp: productData?.mrp,
    sp: productData?.sp,
    barcode: productData?.barcode,
    hsn: productData?.hsn,
    sku: productData?.sku,
    usage: productData?.usage,
    imported_by: productData?.imported_by,
    shelf_life: productData?.shelf_life,
    height: productData?.height,
    width: productData?.width,
    depth: productData?.depth,
    video_link: productData?.video_link,
    video: productData?.video,
    minimum_quantity: productData?.minimum_quantity || 1,
    reserve_quantity: productData?.reserve_quantity || 1,
    Status: productData?.status || 'Available',
    image: productData?.image,
    images: [],
    color_code: productData?.color_code,
    category_name: productData?.category,
    is_premium: productData?.is_premium || false,
    is_try_and_buy: productData?.is_try_and_buy || false,
    is_returnable: productData?.is_returnable || false,
    free_item: productData?.free_item || false,
    sub_category_name: productData?.sub_category,
    product_type_name: productData?.product_type,
    division_name: productData?.division,
    color: productData?.color,
    colorshade: productData?.colorshade,
    skinType: productData?.skintype,
    formulation: productData?.formulation,
    hairType: productData?.hairtype,
    gender: productData?.gender,
    finish: productData?.finish,
    skintone: productData?.skintone,
    coverage: productData?.coverage,
    sunprotection: productData?.sunprotection,
    concious: productData?.concious,
    productHexCode: productData?.productHexCode,
    packsize: productData?.filter_tags?.packsize?.map((item: any) => item).join(','),
    size: productData?.filter_tags?.size?.join('/'),
    ingrediants: productData?.ingredients,
    vegnonveg: productData?.vegnonveg,
    ingrediantsPreferences: productData?.ingrediantsPreferences,
    concern: productData?.concerns,
    recommendationfor: productData?.recommendationfor,
    scenttopnotes: productData?.scenttopnotes,
    scentheartnotes: productData?.scentheartnotes,
    scentbasenotes: productData?.scentbasenotes,
    color_code_link: productData?.color_code_link,
    origincountry: productData?.origincountry || 'India',
    careinstruction: productData?.careinstructions,
    antiodour: productData?.antiodour,
    pattern: productData?.pattern,
    closuretype: productData?.closuretype,
    length: productData?.length,
    necktype: productData?.necktype,
    risetype: productData?.risetype,
    colorfamily: productData?.filter_tags?.colorfamily?.map((item: any) => item).join(','),
    sleevtype: productData?.sleevtype,
    trend: productData?.filter_tags?.trend?.join('/'),
    trendtype: productData?.filter_tags?.trendtype?.join('/'),
    fit: productData?.filter_tags?.fit?.join('/'),
    fabric: productData?.filter_tags?.fabric?.join('/'),
    size_chart_image: productData?.size_chart_image,
    size_chart_image_array: productData?.size_chart_image_array || [],
    filter_tags: productData?.filter_tags,
    is_locked: productData?.is_locked || false,
})
