import Input from '@/components/ui/Input'

export const COUPON_SERIES_FORM = [
    {
        label: 'Campaign Name',
        classname: 'col-span-1 w-full',
        type: 'text',
        name: 'campaign',
        placeholder: 'Enter Campaign Name',
        component: { Input },
        status: 'campaign',
    },
    {
        label: 'Prefix',
        classname: 'col-span-1 w-full',
        type: 'text',
        name: 'prefix',
        placeholder: 'Enter prefix for the coupon',
        component: { Input },
        status: 'prefix',
    },

    {
        label: 'Value',
        classname: 'col-span-1 w-full',
        type: 'number',
        max: 10,
        min: 0,
        name: 'value',
        placeholder: 'Enter coupon value',
        component: { Input },
        status: 'value',
    },
    {
        label: 'Min Cart Value',
        classname: 'col-span-1 w-full',
        type: 'number',
        max: 10,
        min: 0,
        name: 'min_cart_value',
        placeholder: 'Enter minimum cart value',
        component: { Input },
        status: 'min_cart_value',
    },
    {
        label: 'Max Count',
        classname: 'col-span-1 w-full',
        type: 'number',
        max: 10,
        min: 0,
        name: 'max_count',
        placeholder: 'Enter maximum count',
        component: { Input },
        status: 'max_count',
    },
    {
        label: 'Maximum Discount',
        classname: 'col-span-1 w-full',
        type: 'number',
        max: 10,
        min: 0,
        name: 'maximum_discount',
        placeholder: 'Enter maximum price',
        component: { Input },
        status: 'maximum_discount',
    },
    {
        label: 'Maximum Order Count',
        classname: 'col-span-1 w-full',
        type: 'number',
        max: 10,
        min: 0,
        name: 'max_order_count',
        placeholder: 'Enter maximum order Count',
        component: { Input },
        tooltip: 'It is the maximum Order count per user',
    },
    {
        label: 'Minimum Order Count',
        classname: 'col-span-1 w-full',
        type: 'number',
        max: 10,
        min: 0,
        name: 'min_order_count',
        placeholder: 'Enter miminum order Count',
        component: { Input },
        tooltip: 'It is the minimum Order count per user',
    },

    {
        label: 'Max Count Per User',
        classname: 'col-span-1 w-full',
        type: 'number',
        max: 10,
        min: 0,
        name: 'max_count_per_user',
        placeholder: 'Enter maximum count per user',
        component: { Input },
        status: 'max_count_per_user',
    },
    {
        label: 'Minimum Filter Products Amount',
        classname: 'col-span-1 w-full',
        type: 'number',
        max: 10,
        min: 0,
        name: 'extra_attributes.min_filters_products_amount',
        placeholder: 'Enter Minimum Filter Products Amount',
        component: { Input },
        status: 'extra_attributes.min_filters_products_amount',
    },

    {
        label: 'Is Public',
        classname: 'col-span-1 w-full',
        type: 'checkbox',
        name: 'is_public',
        placeholder: 'Enter user',
        component: { Input },
        status: 'is_public',
    },
    {
        label: 'New Users Only',
        classname: 'col-span-1 w-full',
        type: 'checkbox',
        name: 'extra_attributes.new_users_only',
        placeholder: 'Enter user',
        component: { Input },
        status: 'new_users_only',
    },
]
