import Input from '@/components/ui/Input'

export const COUPON_SERIES_FORM = [
    {
        label: 'Campaign Name',
        classname: 'col-span-1 w-full',
        type: 'text',
        name: 'campaign',
        placeholder: 'Enter Campaign Name',
        component: { Input },
        status: 'campaign',
    },
    {
        label: 'Prefix',
        classname: 'col-span-1 w-full',
        type: 'text',
        name: 'prefix',
        placeholder: 'Enter prefix for the coupon',
        component: { Input },
        status: 'prefix',
    },

    {
        label: 'Value',
        classname: 'col-span-1 w-full',
        type: 'number',
        max: 10,
        min: 0,
        name: 'value',
        placeholder: 'Enter coupon value',
        component: { Input },
        status: 'value',
    },
    {
        label: 'Min Cart Value',
        classname: 'col-span-1 w-full',
        type: 'number',
        max: 10,
        min: 0,
        name: 'min_cart_value',
        placeholder: 'Enter minimum cart value',
        component: { Input },
        status: 'min_cart_value',
    },
    {
        label: 'Max Count',
        classname: 'col-span-1 w-full',
        type: 'number',
        max: 10,
        min: 0,
        name: 'max_count',
        placeholder: 'Enter maximum count',
        component: { Input },
        status: 'max_count',
    },
    {
        label: 'Maximum Discount',
        classname: 'col-span-1 w-full',
        type: 'number',
        max: 10,
        min: 0,
        name: 'maximum_discount',
        placeholder: 'Enter maximum price',
        component: { Input },
        status: 'maximum_discount',
    },
    {
        label: 'Maximum Order Count',
        classname: 'col-span-1 w-full',
        type: 'number',
        max: 10,
        min: 0,
        name: 'extra_attributes.max_order_count',
        placeholder: 'Enter maximum order Count',
        component: { Input },
        tooltip: 'It is the maximum Order count per user',
    },
    {
        label: 'Minimum Order Count',
        classname: 'col-span-1 w-full',
        type: 'number',
        max: 10,
        min: 0,
        name: 'extra_attributes.min_order_count',
        placeholder: 'Enter miminum order Count',
        component: { Input },
        tooltip: 'It is the minimum Order count per user',
    },

    {
        label: 'Max Count Per User',
        classname: 'col-span-1 w-full',
        type: 'number',
        max: 10,
        min: 0,
        name: 'max_count_per_user',
        placeholder: 'Enter maximum count per user',
        component: { Input },
        status: 'max_count_per_user',
    },
    {
        label: 'Max Coupons Per User',
        classname: 'col-span-1 w-full',
        type: 'number',
        max: 10,
        min: 0,
        name: 'max_coupons_per_user',
        placeholder: 'Enter maximum coupons per user',
        component: { Input },
        status: 'max_coupons_per_user',
    },
    {
        label: 'Minimum Filter Products Amount',
        classname: 'col-span-1 w-full',
        type: 'number',
        max: 10,
        min: 0,
        name: 'extra_attributes.min_filters_products_amount',
        placeholder: 'Enter Minimum Filter Products Amount',
        component: { Input },
        status: 'extra_attributes.min_filters_products_amount',
    },
    {
        label: 'Min Item Quantity',
        classname: 'col-span-1 w-full',
        type: 'number',
        name: 'extra_attributes.filters.min_item_quantity',
        placeholder: 'Enter Minimum Item Quantity',
        component: { Input },
    },
    {
        label: 'Offer Text',
        classname: 'col-span-1 w-full',
        type: 'text',
        name: 'extra_attributes.offer_text',
        placeholder: 'Enter Offer Text',
        component: { Input },
    },
    {
        label: 'Customer Registered Start',
        classname: 'col-span-1 w-full',
        type: 'date',
        name: 'extra_attributes.user_filters.registration_date.from_date',
    },
    {
        label: 'Customer Registered End',
        classname: 'col-span-1 w-full',
        type: 'date',
        name: 'extra_attributes.user_filters.registration_date.to_date',
    },

    {
        label: 'Max Groups',
        classname: 'col-span-1 w-full',
        type: 'number',
        name: 'extra_attributes.bxgy_config.max_groups',
        placeholder: 'Enter Maximum Groups',
        component: { Input },
    },
    {
        label: 'X Quantity',
        classname: 'col-span-1 w-full',
        type: 'number',
        name: 'extra_attributes.bxgy_config.x_quantity',
        placeholder: 'Enter X Quantity',
        component: { Input },
    },
    {
        label: 'Y Quantity',
        classname: 'col-span-1 w-full',
        type: 'number',
        name: 'extra_attributes.bxgy_config.y_quantity',
        placeholder: 'Enter Y Quantity',
        component: { Input },
    },
    {
        label: 'Y Discount Value',
        classname: 'col-span-1 w-full',
        type: 'number',
        name: 'extra_attributes.bxgy_config.y_discount_value',
        placeholder: 'Enter Y Discount Value',
        component: { Input },
    },
    {
        label: 'Auto Apply',
        classname: 'col-span-1 w-full',
        type: 'checkbox',
        name: 'extra_attributes.auto_apply',
        placeholder: 'Enter auto apply',
        component: { Input },
    },

    {
        label: 'Is Public',
        classname: 'col-span-1 w-full',
        type: 'checkbox',
        name: 'is_public',
        placeholder: 'Enter user',
        component: { Input },
        status: 'is_public',
    },
    {
        label: 'New Users Only',
        classname: 'col-span-1 w-full',
        type: 'checkbox',
        name: 'extra_attributes.new_users_only',
        placeholder: 'Enter user',
        component: { Input },
        status: 'new_users_only',
    },
    {
        label: 'Free Delivery',
        classname: 'col-span-1 w-full',
        type: 'checkbox',
        name: 'extra_attributes.free_delivery',
        placeholder: 'Enter user',
        component: { Input },
        status: 'free_delivery',
    },
]
