/* eslint-disable @typescript-eslint/no-explicit-any */
export const EditInitialValues = (particularRow: any) => {
    return {
        data_type: particularRow.data_type,
        footer_config: particularRow.footer_config,
        header_config: particularRow.header_config,
        component_type: particularRow.component_type,
        section_heading: particularRow.section_heading,
        background_image: particularRow.background_config?.background_image,
        background_video: particularRow.background_config?.background_video,
        sub_header_config: particularRow.sub_header_config,
        mobile_background_image: particularRow.background_config?.mobile_background_image,
        mobile_background_video: particularRow.background_config?.mobile_background_video,
        background_lottie: particularRow.background_config?.background_lottie,
        mobile_background_lottie: particularRow.background_config?.mobile_background_lottie,
        is_section_clickable: particularRow.is_section_clickable,
        is_section_active: particularRow.is_section_active,
        section_filters: particularRow.section_filters,
        grid: particularRow.grid,
        background_config: particularRow?.background_config,
        border: particularRow.border,
        border_style: particularRow.border_style,
        web_border: particularRow.web_border,
        web_border_style: particularRow.web_border_style,
        name: particularRow.name,
        section_border: particularRow?.section_border,
        section_type: particularRow?.section_type,
        web_name: particularRow.web_name,
        name_footer: particularRow.name_footer,
        web_name_footer: particularRow.web_name_footer,
        component_config: particularRow.component_config,
        extra_info: particularRow.extra_info,
        web_section_border: particularRow?.web_section_border,
        order_count: particularRow?.order_count,
        // background_lottie:particularRow.background_config?.background_lottie,
        // mobile_background_lottie:particularRow.background_config?.mobile_background_lottie,
    }
}
