import Input from '@/components/ui/Input'
import Checkbox from '@/components/ui/Checkbox'
import { BANNERMODEL } from '../BannerCommon'

export const BANNER_FIELDS_TYPE = [
    {
        label: 'Name',
        classname: 'col-span-1 w-full',
        type: 'text',
        name: 'name',
        placeholder: 'Place your Name',
        component: { Input },
        status: 'name',
    },
    {
        label: 'Position',
        classname: 'col-span-1 w-full',
        type: 'number',
        name: 'position',
        placeholder: 'Place Positon',
        component: { Input },
        status: 'position',
    },
    {
        label: 'Section Heading',
        classname: 'col-span-1 w-full',
        type: 'text',
        name: 'section_heading',
        placeholder: 'Place your Section Heading',
        component: { Input },
        status: 'section_heading',
    },
    {
        label: 'Parent Banner',
        classname: 'col-span-1 w-full',
        type: 'text',
        name: 'parent_banner',
        placeholder: 'Place your Parent Banner',
        component: { Input },
        status: 'parent_banner',
    },
    {
        label: 'Type',
        classname: 'col-span-1 w-full',
        type: 'text',
        name: 'type',
        placeholder: 'Place your Type',
        component: { Input },
        status: 'type',
    },
    // {
    //     label: 'Image (Web)',
    //     classname: 'col-span-1 w-full',
    //     type: 'text',
    //     name: 'image_web',
    //     placeholder: 'Place your Image URL for Web',
    //     component: { Input },
    //     status: 'image_web',
    // },
    // {
    //     label: 'Image (Mobile)',
    //     classname: 'col-span-1 w-full',
    //     type: 'text',
    //     name: 'image_mobile',
    //     placeholder: 'Place your Image URL for Mobile',
    //     component: { Input },
    //     status: 'image_mobile',
    // },

    {
        label: 'Offer ID',
        classname: 'col-span-1 w-full',
        type: 'text',
        name: 'offer_id',
        placeholder: 'Place your Offer ID',
        component: { Input },
        status: 'offer_id',
    },
    {
        label: 'Page',
        classname: 'col-span-1 w-full',
        type: 'text',
        name: 'page',
        placeholder: 'Place your Page',
        component: { Input },
        status: 'page',
    },
    {
        label: 'Upto Off',
        classname: 'col-span-1 w-full',
        type: 'text',
        name: 'uptooff',
        placeholder: 'Place your Upto Off',
        component: { Input },
        status: 'uptooff',
    },
    {
        label: 'Tags',
        classname: 'col-span-1 w-full',
        type: 'text',
        name: 'tags_input',
        placeholder: 'Place your Tags',
        component: { Input },
        status: 'tags',
    },
    {
        label: 'Footer',
        classname: 'col-span-1 w-full',
        type: 'text',
        name: 'footer',
        placeholder: 'Place your Footer',
        component: { Input },
        status: 'footer',
    },
    {
        label: 'Coupon Code',
        classname: 'col-span-1 w-full',
        type: 'text',
        name: 'coupon_code',
        placeholder: 'Place your Coupon Code',
        component: { Input },
        status: 'coupon_code',
    },

    // {
    //     label: 'Section Background (Web)',
    //     classname: 'col-span-1 w-full',
    //     type: 'text',
    //     name: 'section_background_web',
    //     placeholder: 'Place your Section Background URL for Web',
    //     component: { Input },
    //     status: 'section_background_web',
    // },
    // {
    //     label: 'Section Background (Mobile)',
    //     classname: 'col-span-1 w-full',
    //     type: 'text',
    //     name: 'section_background_mobile',
    //     placeholder: 'Place your Section Background URL for Mobile',
    //     component: { Input },
    //     status: 'section_background_mobile',
    // },
    {
        label: 'Max Price',
        classname: 'col-span-1 w-full',
        type: 'number',
        name: 'max_price',
        placeholder: 'Place your Max Price',
        component: { Input },
        status: 'max_price',
    },
    {
        label: 'Min Price',
        classname: 'col-span-1 w-full',
        type: 'number',
        name: 'min_price',
        placeholder: 'Place your Min Price',
        component: { Input },
        status: 'min_price',
    },
    {
        label: 'Max off %',
        classname: 'col-span-1 w-full',
        type: 'number',
        name: 'max_off',
        placeholder: 'Enter max off %',
        component: { Input },
        status: 'max_off',
    },
    {
        label: 'Min off %',
        classname: 'col-span-1 w-full',
        type: 'number',
        name: 'min_off',
        placeholder: 'Enter min off %',
        component: { Input },
        status: 'min_off',
    },
    {
        label: 'Barcodes',
        classname: 'col-span-1 w-full',
        type: 'text',
        name: 'barcodes',
        placeholder: 'Place your Barcodes',
        component: { Input },
        status: 'barcodes',
    },
    {
        label: 'Redirection URL',
        classname: 'col-span-1 w-full',
        type: 'text',
        name: 'redirection_url',
        placeholder: 'Place your Redirection URL',
        component: { Input },
        status: 'redirection_url',
    },
    {
        label: 'Web Redirection URL',
        classname: 'col-span-1 w-full',
        type: 'text',
        name: 'extra_attributes.web_redirection_url',
        placeholder: 'Place your Web Redirection URL',
        component: { Input },
        status: 'web_redirection_url',
    },
    {
        label: 'Mobile Redirection URL',
        classname: 'col-span-1 w-full',
        type: 'text',
        name: 'extra_attributes.mobile_redirection_url',
        placeholder: 'Place your Mobile Redirection URL',
        component: { Input },
        status: 'mobile_redirection_url',
    },
    {
        label: 'Offers',
        classname: '',
        type: 'checkbox',
        name: 'offers',
        component: { Checkbox },
        status: 'offers',
    },
    {
        label: 'Is Clickable',
        classname: '',
        type: 'checkbox',
        name: 'is_clickable',
        component: { Checkbox },
        status: 'is_clickable',
    },
]

export const getInitialBannerValue = (bannerData: BANNERMODEL | undefined) => ({
    id: bannerData?.id || 0,
    name: bannerData?.name || '',
    section_heading: bannerData?.section_heading || '',
    parent_banner: bannerData?.parent_banner || null,
    quick_filter_tags: bannerData?.quick_filter_tags || [],
    brand: bannerData?.brand || [],
    division: bannerData?.division || [],
    category: bannerData?.category || [],
    image_web_array: bannerData?.image_web_array || [],
    image_mobile_array: bannerData?.image_mobile_array || [],

    video_web_array: bannerData?.video_web_array || [],
    video_mobile_array: bannerData?.video_mobile_array || [],
    lottie_web_array: bannerData?.lottie_web_array || [],
    lottie_mobile_array: bannerData?.lottie_mobile_array || [],
    extra_attributes: bannerData?.extra_attributes || {},
    sub_category: bannerData?.sub_category || [],
    product_type: bannerData?.product_type || [],
    type: bannerData?.type || null,
    image_web: bannerData?.image_web || '',
    image_mobile: bannerData?.image_mobile || '',
    video_web: bannerData?.video_web || '',
    video_mobile: bannerData?.video_mobile || '',
    offers: bannerData?.offers || false,
    offer_id: bannerData?.offer_id || '',
    page: bannerData?.page || '',
    from_date: bannerData?.from_date || null,
    to_date: bannerData?.to_date || null,
    uptooff: bannerData?.uptooff || '',
    tags: bannerData?.tags || [],
    footer: bannerData?.footer || null,
    coupon_code: bannerData?.coupon_code || null,
    is_clickable: bannerData?.is_clickable || false,
    section_background_web: bannerData?.section_background_web || '',
    section_background_web_array: bannerData?.section_background_web_array || [],
    section_background_mobile_array: bannerData?.section_background_mobile_array || [],
    section_background_mobile: bannerData?.section_background_mobile || '',
    max_price: bannerData?.max_price || 0,
    min_price: bannerData?.min_price || 0,
    max_off: bannerData?.extra_attributes?.maxoff || 0,
    min_off: bannerData?.extra_attributes?.minoff || 0,
    barcodes: bannerData?.barcodes || '',
    redirection_url: bannerData?.redirection_url || null,
    tags_input: bannerData?.tags?.join(',') || '',
    position: bannerData?.position || null,
})
